In [1]:
import pandas as pd
df= pd.read_csv('C:/Users/pc lenevo/Desktop/covid_3scenario/data_complet/owid-covid-data.csv') # having First.csv zipped file.
df.head(50)

,iso_code,continent,location,date,total_cases,new_cases,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,...,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy
0,AFG,Asia,Afghanistan,2019-12-31,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
1,AFG,Asia,Afghanistan,2020-01-01,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
2,AFG,Asia,Afghanistan,2020-01-02,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
3,AFG,Asia,Afghanistan,2020-01-03,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
4,AFG,Asia,Afghanistan,2020-01-04,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
5,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
6,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
7,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
8,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
9,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
10,AFG,Asia,Afghanistan,2020-01-10,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
11,AFG,Asia,Afghanistan,2020-01-11,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
12,AFG,Asia,Afghanistan,2020-01-12,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
13,AFG,Asia,Afghanistan,2020-01-13,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
14,AFG,Asia,Afghanistan,2020-01-14,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
15,AFG,Asia,Afghanistan,2020-01-15,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
16,AFG,Asia,Afghanistan,2020-01-16,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
17,AFG,Asia,Afghanistan,2020-01-17,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
18,AFG,Asia,Afghanistan,2020-01-18,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
19,AFG,Asia,Afghanistan,2020-01-19,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
20,AFG,Asia,Afghanistan,2020-01-20,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
21,AFG,Asia,Afghanistan,2020-01-21,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
22,AFG,Asia,Afghanistan,2020-01-22,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
23,AFG,Asia,Afghanistan,2020-01-23,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
24,AFG,Asia,Afghanistan,2020-01-24,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
25,AFG,Asia,Afghanistan,2020-01-25,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
26,AFG,Asia,Afghanistan,2020-01-26,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
27,AFG,Asia,Afghanistan,2020-01-27,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
28,AFG,Asia,Afghanistan,2020-01-28,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
29,AFG,Asia,Afghanistan,2020-01-29,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
30,AFG,Asia,Afghanistan,2020-01-30,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
31,AFG,Asia,Afghanistan,2020-01-31,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
32,AFG,Asia,Afghanistan,2020-02-01,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
33,AFG,Asia,Afghanistan,2020-02-02,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
34,AFG,Asia,Afghanistan,2020-02-03,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
35,AFG,Asia,Afghanistan,2020-02-04,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
36,AFG,Asia,Afghanistan,2020-02-05,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
37,AFG,Asia,Afghanistan,2020-02-06,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
38,AFG,Asia,Afghanistan,2020-02-07,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
39,AFG,Asia,Afghanistan,2020-02-08,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
40,AFG,Asia,Afghanistan,2020-02-09,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
41,AFG,Asia,Afghanistan,2020-02-10,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
42,AFG,Asia,Afghanistan,2020-02-11,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
43,AFG,Asia,Afghanistan,2020-02-12,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
44,AFG,Asia,Afghanistan,2020-02-13,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
45,AFG,Asia,Afghanistan,2020-02-14,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
46,AFG,Asia,Afghanistan,2020-02-15,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
47,AFG,Asia,Afghanistan,2020-02-16,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
48,AFG,Asia,Afghanistan,2020-02-17,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83
49,AFG,Asia,Afghanistan,2020-02-18,0.0,0.0,0.0,0.0,0.0,0.0,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83

In [2]:
df.date= pd.to_datetime(df['date'],format='%Y-%m-%d')

In [3]:
df=df[['new_cases','total_cases','total_deaths','new_deaths', 'population','date','location']]

In [4]:
df = df.fillna(df.median())

In [5]:
#df['month'] = df['date'].dt.month

In [6]:
#df = df.astype(float)
#df['day'] = df.index.weekday
#df['week'] = df.index.week

In [7]:
start_date = '2020-03-02'
end_date = '2020-08-06'
start_date2 = '2020-08-07'
end_date2 = '2020-08-15'

In [8]:
#mask = (covid_data['date'] >= start_date) & (covid_data['date'] <= end_date) &  (covid_data['location'].isin(['Morocco']))
mask1 = (df['date'] >= start_date) & (df['date'] <= end_date) &  (df['location'].isin(['Morocco']))

In [9]:
mask2 = (df['date'] > start_date2) & (df['date'] <= end_date2) &  (df['location'].isin(['Morocco']))

In [10]:
df.sort_values(by=['location'], inplace=True)

In [11]:
X_train = df.loc[mask1]
X_train.shape

(158, 7)

In [12]:
X_test = df.loc[mask2]

X_test.shape

(8, 7)

In [13]:
X_test['timestamp'] = pd.to_datetime(X_test['date'], infer_datetime_format=True)
X_test.set_index('timestamp', inplace=True)

X_train['timestamp'] = pd.to_datetime(X_train['date'], infer_datetime_format=True)
X_train.set_index('timestamp', inplace=True)

C:\Users\pc lenevo\.conda\envs\ImanEnv\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\pc lenevo\.conda\envs\ImanEnv\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [14]:
X_train=X_train[['new_cases','total_cases','total_deaths', 'new_deaths', 'population']]

X_test=X_test[['new_cases','total_cases','total_deaths', 'new_deaths', 'population']]
Y_test=X_test[['new_cases']]

Y_train=X_train[['new_cases']]

In [15]:
days=X_test.index
days=days.sort_values()

In [16]:
nb_seq=1
days=days[nb_seq:]

In [17]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(158, 5)
(158, 1)
(8, 5)
(8, 1)

In [18]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0, 1))
scaler2= MinMaxScaler(feature_range=(0, 1))

In [19]:
nb_col=5
nb_seq=1
n_out=7

In [20]:
from math import sqrt
from numpy import concatenate
from matplotlib import pyplot
from pandas import read_csv
from pandas import DataFrame
from pandas import concat
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from keras.models import Sequential
from keras.layers import Dense

from keras.layers import GRU, LSTM, CuDNNGRU, CuDNNLSTM, Activation
# convert series to supervised learning
def series_to_supervised(data, n_in=1, n_out=1, dropnan=True):
    n_vars = 1 if type(data) is list else data.shape[1]
    df = DataFrame(data)
    cols, names = list(), list()
    # input sequence (t-n, ... t-1)
    for i in range(n_in, 0, -1):
        cols.append(df.shift(i))
        names += [('var%d(t-%d)' % (j+1, i)) for j in range(n_vars)]
    # forecast sequence (t, t+1, ... t+n)
    for i in range(0, n_out):
        cols.append(df.shift(-i))
        if i == 0:
            names += [('var%d(t)' % (j+1)) for j in range(n_vars)]
        else:
            names += [('var%d(t+%d)' % (j+1, i)) for j in range(n_vars)]
    # put it all together
    agg = concat(cols, axis=1)
    agg.columns = names
    # drop rows with NaN values
    if dropnan:
        agg.dropna(inplace=True)
    return agg

X_train=X_train.values
X_test=X_test.values
Y_train=Y_train.values
Y_test=Y_test.values





# ensure all data is float
X_train = X_train.astype('float32')
# ensure all data is float
X_test = X_test.astype('float32')
# ensure all data is float
Y_test = Y_test.astype('float32')
# ensure all data is float
Y_train = Y_train.astype('float32')

# normalize features


X_train= scaler.fit_transform(X_train)
X_test= scaler.fit_transform(X_test)
Y_train= scaler2.fit_transform(Y_train)
Y_test= scaler2.fit_transform(Y_test)

# reframe as supervised learning
X_train = series_to_supervised(X_train, nb_seq, n_out)
X_test = series_to_supervised(X_test,  nb_seq, n_out)
print(X_train)
print(X_train.shape)
print(X_test.shape)
Y_train = series_to_supervised(Y_train,  nb_seq, n_out)
Y_test = series_to_supervised(Y_test,  nb_seq, n_out)
print(Y_train.shape)
print(Y_test.shape)

Using TensorFlow backend.

     var1(t-1)  var2(t-1)  var3(t-1)  var4(t-1)  var5(t-1)   var1(t)  \
1     0.306313   0.498754   0.540230   0.157895        0.0  0.248636
2     0.248636   0.466227   0.528736   0.052632        0.0  0.080281
3     0.080281   0.443349   0.524138   0.000000        0.0  0.416212
4     0.416212   0.484964   0.533333   0.105263        0.0  0.259548
5     0.259548   0.455034   0.526437   0.052632        0.0  0.158223
..         ...        ...        ...        ...        ...       ...
147   0.108340   0.136707   0.365517   0.052632        0.0  0.109119
148   0.109119   0.194638   0.420690   0.000000        0.0  0.147311
149   0.147311   0.189726   0.420690   0.105263        0.0  0.137178
150   0.137178   0.183094   0.416092   0.105263        0.0  0.135620
151   0.135620   0.172006   0.400000   0.052632        0.0  0.109119

      var2(t)   var3(t)   var4(t)  var5(t)  ...  var1(t+5)  var2(t+5)  \
1    0.466227  0.528736  0.052632      0.0  ...   0.295401   0.537808
2    0.443349  0.524138  0.000000      0.0  ...   0.000000   0.502754
3    0.484964  0.533333  0.105263      0.0  ...   0.344505   0.518264
4    0.455034  0.526437  0.052632      0.0  ...   0.138737   0.524510
5    0.552440  0.574713  0.263158      0.0  ...   0.189400   0.439735
..        ...       ...       ...      ...  ...        ...        ...
147  0.194638  0.420690  0.000000      0.0  ...   0.113796   0.160286
148  0.189726  0.420690  0.105263      0.0  ...   0.079501   0.155163
149  0.183094  0.416092  0.105263      0.0  ...   0.053780   0.151584
150  0.172006  0.400000  0.052632      0.0  ...   0.102884   0.149163
151  0.176918  0.411494  0.263158      0.0  ...   0.042868   0.144531

     var3(t+5)  var4(t+5)  var5(t+5)  var1(t+6)  var2(t+6)  var3(t+6)  \
1     0.558621   0.052632        0.0   0.000000   0.502754   0.540230
2     0.540230   0.000000        0.0   0.344505   0.518264   0.556322
3     0.556322   0.368421        0.0   0.138737   0.524510   0.556322
4     0.556322   0.000000        0.0   0.189400   0.439735   0.524138
5     0.524138   0.157895        0.0   0.166797   0.545317   0.563218
..         ...        ...        ...        ...        ...        ...
147   0.393103   0.052632        0.0   0.079501   0.155163   0.390805
148   0.390805   0.105263        0.0   0.053780   0.151584   0.386207
149   0.386207   0.157895        0.0   0.102884   0.149163   0.379310
150   0.379310   0.157895        0.0   0.042868   0.144531   0.372414
151   0.372414   0.052632        0.0   0.124708   0.165901   0.397701

     var4(t+6)  var5(t+6)
1     0.000000        0.0
2     0.368421        0.0
3     0.000000        0.0
4     0.157895        0.0
5     0.105263        0.0
..         ...        ...
147   0.105263        0.0
148   0.157895        0.0
149   0.157895        0.0
150   0.052632        0.0
151   0.105263        0.0

[151 rows x 40 columns]
(151, 40)
(1, 40)
(151, 8)
(1, 8)

In [21]:
col_y_need_train=X_train.columns[[5,10,15,20,25,30,35]]
col_y_need_test=X_test.columns[[5,10,15,20,25,30,35]]
X_train

,var1(t-1),var2(t-1),var3(t-1),var4(t-1),var5(t-1),var1(t),var2(t),var3(t),var4(t),var5(t),...,var1(t+5),var2(t+5),var3(t+5),var4(t+5),var5(t+5),var1(t+6),var2(t+6),var3(t+6),var4(t+6),var5(t+6)
1,0.306313,0.498754,0.540230,0.157895,0.0,0.248636,0.466227,0.528736,0.052632,0.0,...,0.295401,0.537808,0.558621,0.052632,0.0,0.000000,0.502754,0.540230,0.000000,0.0
2,0.248636,0.466227,0.528736,0.052632,0.0,0.080281,0.443349,0.524138,0.000000,0.0,...,0.000000,0.502754,0.540230,0.000000,0.0,0.344505,0.518264,0.556322,0.368421,0.0
3,0.080281,0.443349,0.524138,0.000000,0.0,0.416212,0.484964,0.533333,0.105263,0.0,...,0.344505,0.518264,0.556322,0.368421,0.0,0.138737,0.524510,0.556322,0.000000,0.0
4,0.416212,0.484964,0.533333,0.105263,0.0,0.259548,0.455034,0.526437,0.052632,0.0,...,0.138737,0.524510,0.556322,0.000000,0.0,0.189400,0.439735,0.524138,0.157895,0.0
5,0.259548,0.455034,0.526437,0.052632,0.0,0.158223,0.552440,0.574713,0.263158,0.0,...,0.189400,0.439735,0.524138,0.157895,0.0,0.166797,0.545317,0.563218,0.105263,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,0.108340,0.136707,0.365517,0.052632,0.0,0.109119,0.194638,0.420690,0.000000,0.0,...,0.113796,0.160286,0.393103,0.052632,0.0,0.079501,0.155163,0.390805,0.105263,0.0
148,0.109119,0.194638,0.420690,0.000000,0.0,0.147311,0.189726,0.420690,0.105263,0.0,...,0.079501,0.155163,0.390805,0.105263,0.0,0.053780,0.151584,0.386207,0.157895,0.0
149,0.147311,0.189726,0.420690,0.105263,0.0,0.137178,0.183094,0.416092,0.105263,0.0,...,0.053780,0.151584,0.386207,0.157895,0.0,0.102884,0.149163,0.379310,0.157895,0.0
150,0.137178,0.183094,0.416092,0.105263,0.0,0.135620,0.172006,0.400000,0.052632,0.0,...,0.102884,0.149163,0.379310,0.157895,0.0,0.042868,0.144531,0.372414,0.052632,0.0
151,0.135620,0.172006,0.400000,0.052632,0.0,0.109119,0.176918,0.411494,0.263158,0.0,...,0.042868,0.144531,0.372414,0.052632,0.0,0.124708,0.165901,0.397701,0.105263,0.0

In [22]:
# drop columns we don't want to predict
Y_train = X_train[col_y_need_train]
Y_test=X_test[col_y_need_test]
Y_train
print(Y_train.shape)
print(Y_test.shape)

(151, 7)
(1, 7)

In [23]:
print(Y_train)

      var1(t)  var1(t+1)  var1(t+2)  var1(t+3)  var1(t+4)  var1(t+5)  \
1    0.248636   0.080281   0.416212   0.259548   0.158223   0.295401
2    0.080281   0.416212   0.259548   0.158223   0.295401   0.000000
3    0.416212   0.259548   0.158223   0.295401   0.000000   0.344505
4    0.259548   0.158223   0.295401   0.000000   0.344505   0.138737
5    0.158223   0.295401   0.000000   0.344505   0.138737   0.189400
..        ...        ...        ...        ...        ...        ...
147  0.109119   0.147311   0.137178   0.135620   0.109119   0.113796
148  0.147311   0.137178   0.135620   0.109119   0.113796   0.079501
149  0.137178   0.135620   0.109119   0.113796   0.079501   0.053780
150  0.135620   0.109119   0.113796   0.079501   0.053780   0.102884
151  0.109119   0.113796   0.079501   0.053780   0.102884   0.042868

     var1(t+6)
1     0.000000
2     0.344505
3     0.138737
4     0.189400
5     0.166797
..         ...
147   0.079501
148   0.053780
149   0.102884
150   0.042868
151   0.124708

[151 rows x 7 columns]

In [24]:
col_y_need_trainX=X_train.columns[[0,1,2,3,4]]
col_y_need_testX=X_test.columns[[0,1,2,3,4]]

In [25]:
# drop columns we don't want to predict
X_train = X_train[col_y_need_trainX]
X_test=X_test[col_y_need_testX]
print(X_train.shape)
print(X_test.shape)
X_train

(151, 5)
(1, 5)

     var1(t-1)  var2(t-1)  var3(t-1)  var4(t-1)  var5(t-1)
1     0.306313   0.498754   0.540230   0.157895        0.0
2     0.248636   0.466227   0.528736   0.052632        0.0
3     0.080281   0.443349   0.524138   0.000000        0.0
4     0.416212   0.484964   0.533333   0.105263        0.0
5     0.259548   0.455034   0.526437   0.052632        0.0
..         ...        ...        ...        ...        ...
147   0.108340   0.136707   0.365517   0.052632        0.0
148   0.109119   0.194638   0.420690   0.000000        0.0
149   0.147311   0.189726   0.420690   0.105263        0.0
150   0.137178   0.183094   0.416092   0.105263        0.0
151   0.135620   0.172006   0.400000   0.052632        0.0

[151 rows x 5 columns]

In [26]:
print(X_test.shape)

(1, 5)

In [27]:
X_train=X_train.values
X_test=X_test.values

Y_train=Y_train.values
Y_test=Y_test.values

# reshape input to be 3D [samples, timesteps, features]
X_test = X_test.reshape((X_test.shape[0], nb_seq, nb_col))
X_train = X_train.reshape((X_train.shape[0], nb_seq, nb_col))

print(X_test.shape, Y_test.shape, X_train.shape, Y_train.shape)

(1, 1, 5) (1, 7) (151, 1, 5) (151, 7)

In [28]:
n_input = X_train.shape[1] * X_train.shape[2]
X_train= X_train.reshape((X_train.shape[0], n_input))
n_input2 = X_test.shape[1] * X_test.shape[2]
X_test= X_test.reshape((X_test.shape[0], n_input2))

print(X_test.shape, Y_test.shape, X_train.shape, Y_train.shape)

(1, 5) (1, 7) (151, 5) (151, 7)

In [29]:
# IMPORT ML Regressor
from sklearn.linear_model import LinearRegression # Linear regression
from sklearn.ensemble import RandomForestRegressor # random forest regression
from sklearn.neural_network import MLPRegressor # neural network regression
from sklearn.svm import SVR # support vector regression

In [30]:
reg = SVR()
reg.fit(X_train, Y_train)

ValueError: bad input shape (151, 7)

In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error


# make a prediction
yhat = reg.predict(X_test)
# invert scaling for forecast
inv_yhat = scaler2.inverse_transform(yhat)
#print(inv_yhat)
# invert scaling for actual
Y_test = Y_test.reshape((len(Y_test), 7))
inv_y = scaler2.inverse_transform(Y_test)
#print(inv_y)
# calculate errors


# make a prediction
yhat_train = reg.predict(X_train)
# invert scaling for forecast
inv_yhat_train = scaler2.inverse_transform(yhat_train)
print(inv_yhat_train)
# invert scaling for actual
Y_train = Y_train.reshape((len(Y_train), 7))
inv_y_train = scaler2.inverse_transform(Y_train)
print(inv_y_train)
# calculate errors

In [ ]:
p1 = pd.DataFrame(data=inv_yhat)
p1= p1.transpose()
print(days)

In [ ]:
t1 = pd.DataFrame(data=inv_y)
t1= t1.transpose()

In [ ]:
test_res=pd.DataFrame()
test_res['Prediction']=p1[0]
test_res['real']=t1[0]
test_res.set_index(days,inplace=True)

In [ ]:
test_res

In [ ]:
import numpy as np 
from sklearn import metrics
print('Test results')
print('MAE:', round(metrics.mean_absolute_error(test_res['real'], test_res['Prediction']), 2))
print('MSE:', round(metrics.mean_squared_error(test_res['real'], test_res['Prediction']), 2))
print('RMSE:',round( np.sqrt(metrics.mean_squared_error(test_res['real'], test_res['Prediction'])), 2))
print('R Squared:', round( metrics.r2_score(test_res['real'], test_res['Prediction']), 2))
print('Max Error:',round(  metrics.max_error(test_res['real'], test_res['Prediction']), 2))

In [ ]:

import pandas as pd
import numpy as np; np.random.seed(1)
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(15,7))
plt.plot(test_res.index, test_res['real'],  label='Actual Values')
plt.plot(test_res.index, test_res['Prediction'], label='Predicted Values')
# If you don't like the break in the graph, change 90 to 89 in the above line
plt.gcf().autofmt_xdate()
plt.legend()
plt.show()